Improve query interface for get recordings page
TheCacophonyProject/cacophony-web-old pull request #79
Opened 2018-06-19 23:53 UTC by arthurmcgregor

Significant changes to the get recordings page.

- Changed layout of columns to be more responsive (#76)
- Changed terms for date selection. Before date and after date become From Date and To Date (which makes more sense to me)
- Replaced longer than, shorter than with duration range slider
- Duration range slider initially has range from 0 to 100 s, however clicking the arrow will increase the max range by 100s (up to 600s)
- Date and duration automatically create new conditions (and remove old conditions) when their input changes. _I am assuming you only ever want one set of bounds for each condition_
- Conditions have been hidden. Now that they always reflect the dates and duration boxes you do not need to see them or delete old conditions.
- Shifted device and tag selectors to the top of the page. _I am assuming these are more commonly used_
- Rearranged limit and offset to be closer to table
- Rearranged other buttons
- Added table-responsive class to table which means it becomes scroll-able on small screens (better than alternative)

So hopefully that all works and is an improvement.

A few questions (because I don't really know how this is actually used!)
- Are devices and tags the most commonly used query fields, or should something else be at the top of the page?
- Do you ever want to filter by (devices || tags) && (duration || date)? Because 'get all' only does (devices || tags) and 'get all from conditions' only does (date || duration). I feel these two could be combined into one 'Search' button or 'Filter' or 'Get recordings'
- Do you ever want to choose several devices? ie a checklist rather than a drop down list
- Ditto for tags

Screenshots
Desktop size - before
![desktop1](https://user-images.githubusercontent.com/24260476/41629938-6c734dd0-7480-11e8-8c55-959c2536dd8f.png)
Desktop size - after
![desktop2](https://user-images.githubusercontent.com/24260476/41629939-6ca0bbe4-7480-11e8-8722-69a59892f6bc.png)
Mobile size - before
![mobile1](https://user-images.githubusercontent.com/24260476/41629940-6cce1062-7480-11e8-89d6-a289bd64d179.png)
Mobile size - after
![mobile2](https://user-images.githubusercontent.com/24260476/41629941-6cfd3a9a-7480-11e8-8941-7b37d1289dcb.png)

2018-06-20 00:33 UTC, mjs commented
This is excellent. Thanks! Answers to your questions:

**Are devices and tags the most commonly used query fields, or should something else be at the top of the page?**

The device and tags fields are the most common ones.

**Do you ever want to filter by (devices || tags) && (duration || date)? Because 'get all' only does (devices || tags) and 'get all from conditions' only does (date || duration). I feel these two could be combined into one 'Search' button or 'Filter' or 'Get recordings'**

There should be just one button. I like "Search" as the name for it.

**Do you ever want to choose several devices? ie a checklist rather than a drop down list**

Not really, but we would like to be able to filter by "device group". We'll have to figure out how to query the API for that.

**Ditto for tags**

The field called "Tags" should actually be called "Tag type" or "Tag class". The current combinations in the drop down are all we need right now.

At some stage we need to add searching by tag (i.e. animal). That would be nice to do as a series of checkboxes.

See my email too for more UI suggestions. No need to do them all in one PR though. This is a great start.

I'll leave the code review for @CameronRP .

2018-06-20 01:40 UTC, CameronRP requested changes
Nice work! Looks much better. Just one little fix.

2018-06-20 01:40 UTC, CameronRP commented on public/javascripts/getRecordings.js
>    updateConditions();
Removing the conditions element is causing `updateConditions()` function to error. This then causes the `addToDate()` and other similar functions to error causing unwanted behavior. Simple fix should be to delete this function and all it's references.

2018-06-20 01:49 UTC, arthurmcgregor commented on public/javascripts/getRecordings.js
>    updateConditions();
Great thanks. I initially kept it in there for debugging.... but totally gone now :-)

2018-06-20 01:49 UTC, arthurmcgregor commented
Thanks for your email and feedback @mjs. Will look to incorporate those ideas as well...

2018-06-20 01:53 UTC, mjs commented
@arthurmcgregor Did you want to land this and then propose more PRs with some of the other suggestions?

2018-06-20 01:55 UTC, arthurmcgregor commented
@mjs Yup will do :-)

2018-06-20 01:59 UTC, CameronRP approved these changes

2018-06-20 02:08 UTC, merged

2018-06-20 02:26 UTC, CameronRP commented
@arthurmcgregor Code is now live on the test server :) https://browse-test.cacophony.org.nz/get_recordings

2018-06-20 09:01 UTC, arthurmcgregor commented
Yay! Now I can see how well it works on an actual mobile phone...

Plus summarised all of these ideas in #81

2018-06-21 08:25 UTC, mjs commented
@arthurmcgregor it's already so much better - thank you! Looking forward to seeing what else you come up with.