Upgrade bootstrap to version 4
TheCacophonyProject/cacophony-web-old pull request #80
Opened 2018-06-20 08:53 UTC by arthurmcgregor

#76 improving mobile experience is easier with the newer version of bootstrap.... so I have upgraded most of our pages to use bootstrap 4 👍 

The following pages are still using bootstrap 3:
- setupAudio.pug
- viewAudioRecording.pug
- viewRecording.pug
These are complex pages! Can easily be converted to bootstrap 4 when they have their styling reviewed. To keep them at bootstrap 3, there is an explicit include statement for bootstrap 3 in the head.

All other pages using bootstrap 4 have an explicit include statement for bootstrap 4 in the head, plus a footer at the end of the body which adds the required scripts.

I have not upgraded to the latest version of jQuery (to match the upgraded bootstrap) because it broke Ajax! Not sure if this will affect any bootstrap features or not... seems to be working ok at the moment.

2018-06-20 22:48 UTC, arthurmcgregor commented
Need to restore form validation and error messages to login and register pages

2018-06-21 08:26 UTC, mjs commented
@arthurmcgregor I'm happy with the partial approach with converting to Bootstrap v4. Can you please create an issue (or issues) for the pages that still need to be converted so that we're tracking this?

2018-06-21 08:26 UTC, mjs commented
@CameronRP can you review this when you have a chance please?

2018-06-21 22:11 UTC, CameronRP requested changes
Looking much nicer. Just these couple of things and also as you said restoring error the messages to login and register pages.

2018-06-21 22:11 UTC, CameronRP commented on views/includes/getQuery.pug
> -    input(type='button', value='Add', onClick="queryUtil.addDeviceId()")
The new layout for the inputs for "Make new condition" takes up a lot of vertical space on the page. If you could make the label and inputs on the same line this should save a lot of space on the page.

2018-06-21 22:11 UTC, CameronRP commented on views/includes/getQuery.pug
> -  input#offset.col-md-2(type='number', value=0)
If you could make the Limit and Offset inputs a bit wider here so it's easier to see there values.

2018-06-22 05:12 UTC, arthurmcgregor commented on views/includes/getQuery.pug
> -    input(type='button', value='Add', onClick="queryUtil.addDeviceId()")
Yup it's on the list of ones to fix better #82. I've reverted it back to the bootstrap 3 version which takes up less vertical space so the page should be usable again. However, I don't want it to hold up the PR so will deal with it later...

2018-06-22 05:12 UTC, arthurmcgregor commented on views/includes/getQuery.pug
> -  input#offset.col-md-2(type='number', value=0)
Ditto

2018-06-22 05:13 UTC, arthurmcgregor commented on views/includes/getQuery.pug
> -    input(type='button', value='Add', onClick="queryUtil.addDeviceId()")
The idea would be for it to get a similar treatment to the getRecordings.pug page - in fact if the API request functionality is similar, could they be a common component? I'm assuming that was the idea behind a separate getQuery.pug file but seemingly not implemented...

2018-06-22 08:15 UTC, CameronRP approved these changes

2018-06-22 23:24 UTC, merged